version: 2.1

jobs:

  # build-and-junit-test:
  #   docker:
  #     - image: cimg/openjdk:11.0
  #   steps:
  #     - checkout
  #     - run:
  #         name: Build
  #         command: mvn -B -DskipTests clean package
  #     - run:
  #         name: Junit Test
  #         command: 
  # build-and-junit-test:
  #   docker:
  #     - image: circleci/openjdk:8-jdk
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - run: mvn install
  #     - store_test_results:
  #         path: target/surefire-reports
  build-and-junit-test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run: mvn install
      - store_test_results:
          path: target/surefire-reports


workflows:
  sample: 
    jobs:
      - build-and-junit-test
