version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: mvn install
      - store_test_results:
          path: target/surefire-reports


workflows:
  sample: 
    jobs:
      - build-and-test
      - docker/publish:
          image: circleci-springboot 
          deploy: true
          requires:
            - build-and-test